# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_SoilTexture.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SoilTexture(object):
    def setupUi(self, SoilTexture):
        SoilTexture.setObjectName("SoilTexture")
        SoilTexture.resize(478, 459)
        self.toolBox = QtWidgets.QToolBox(SoilTexture)
        self.toolBox.setGeometry(QtCore.QRect(8, 12, 451, 421))
        self.toolBox.setObjectName("toolBox")
        self.TexturePage = QtWidgets.QWidget()
        self.TexturePage.setGeometry(QtCore.QRect(0, 0, 451, 367))
        self.TexturePage.setObjectName("TexturePage")
        self.groupBox_5 = QtWidgets.QGroupBox(self.TexturePage)
        self.groupBox_5.setGeometry(QtCore.QRect(230, 230, 201, 61))
        self.groupBox_5.setObjectName("groupBox_5")
        self.cmbSchema = QtWidgets.QComboBox(self.groupBox_5)
        self.cmbSchema.setGeometry(QtCore.QRect(20, 20, 151, 25))
        self.cmbSchema.setMinimumSize(QtCore.QSize(0, 25))
        self.cmbSchema.setMaximumSize(QtCore.QSize(16777215, 25))
        self.cmbSchema.setObjectName("cmbSchema")
        self.groupBox = QtWidgets.QGroupBox(self.TexturePage)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 421, 121))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 401, 91))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblClay = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.lblClay.setMaximumSize(QtCore.QSize(50, 20))
        self.lblClay.setObjectName("lblClay")
        self.gridLayout_3.addWidget(self.lblClay, 1, 0, 1, 1)
        self.lblSand = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.lblSand.setMaximumSize(QtCore.QSize(50, 20))
        self.lblSand.setAutoFillBackground(False)
        self.lblSand.setObjectName("lblSand")
        self.gridLayout_3.addWidget(self.lblSand, 0, 0, 1, 1)
        self.cmbClay = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.cmbClay.setMinimumSize(QtCore.QSize(280, 25))
        self.cmbClay.setMaximumSize(QtCore.QSize(300, 25))
        self.cmbClay.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cmbClay.setObjectName("cmbClay")
        self.gridLayout_3.addWidget(self.cmbClay, 1, 1, 1, 1)
        self.cmbSand = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.cmbSand.setMinimumSize(QtCore.QSize(280, 25))
        self.cmbSand.setMaximumSize(QtCore.QSize(300, 25))
        self.cmbSand.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cmbSand.setObjectName("cmbSand")
        self.gridLayout_3.addWidget(self.cmbSand, 0, 1, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.TexturePage)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 300, 401, 52))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.gridLayoutWidget)
        self.buttonBox.setMinimumSize(QtCore.QSize(0, 25))
        self.buttonBox.setMaximumSize(QtCore.QSize(16777215, 25))
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setAutoFillBackground(True)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_5.addWidget(self.buttonBox, 0, 1, 1, 1)
        self.btnHelp = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnHelp.setObjectName("btnHelp")
        self.gridLayout_5.addWidget(self.btnHelp, 0, 2, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.TexturePage)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 230, 201, 61))
        self.groupBox_4.setStyleSheet("border-color: rgb(4, 4, 4);")
        self.groupBox_4.setObjectName("groupBox_4")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_4)
        self.progressBar.setGeometry(QtCore.QRect(20, 20, 159, 25))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.groupBox_2 = QtWidgets.QGroupBox(self.TexturePage)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 130, 421, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 401, 51))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineOutput = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineOutput.setMinimumSize(QtCore.QSize(280, 25))
        self.lineOutput.setMaximumSize(QtCore.QSize(280, 25))
        self.lineOutput.setObjectName("lineOutput")
        self.gridLayout.addWidget(self.lineOutput, 2, 1, 1, 1)
        self.btnOutput = QtWidgets.QToolButton(self.gridLayoutWidget_2)
        self.btnOutput.setMinimumSize(QtCore.QSize(0, 25))
        self.btnOutput.setMaximumSize(QtCore.QSize(16777215, 25))
        self.btnOutput.setObjectName("btnOutput")
        self.gridLayout.addWidget(self.btnOutput, 2, 0, 1, 1)
        self.toolBox.addItem(self.TexturePage, "")
        self.MessagesPage = QtWidgets.QWidget()
        self.MessagesPage.setGeometry(QtCore.QRect(0, 0, 451, 367))
        self.MessagesPage.setObjectName("MessagesPage")
        self.groupBox_3 = QtWidgets.QGroupBox(self.MessagesPage)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 12, 441, 341))
        self.groupBox_3.setObjectName("groupBox_3")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit.setGeometry(QtCore.QRect(10, 20, 411, 311))
        self.textEdit.setObjectName("textEdit")
        self.toolBox.addItem(self.MessagesPage, "")

        self.retranslateUi(SoilTexture)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SoilTexture)

    def retranslateUi(self, SoilTexture):
        _translate = QtCore.QCoreApplication.translate
        SoilTexture.setWindowTitle(_translate("SoilTexture", "SoilTexture"))
        self.groupBox_5.setTitle(_translate("SoilTexture", "Texture scheme"))
        self.groupBox.setTitle(_translate("SoilTexture", "Input "))
        self.lblClay.setText(_translate("SoilTexture", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Clay</span></p></body></html>"))
        self.lblSand.setText(_translate("SoilTexture", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Sand</span></p></body></html>"))
        self.btnHelp.setText(_translate("SoilTexture", "Help"))
        self.groupBox_4.setTitle(_translate("SoilTexture", "Progress..."))
        self.groupBox_2.setTitle(_translate("SoilTexture", "Output "))
        self.btnOutput.setText(_translate("SoilTexture", "..."))
        self.toolBox.setItemText(self.toolBox.indexOf(self.TexturePage), _translate("SoilTexture", "Texture"))
        self.groupBox_3.setTitle(_translate("SoilTexture", "Messages"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.MessagesPage), _translate("SoilTexture", "Messages"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SoilTexture = QtWidgets.QDialog()
    ui = Ui_SoilTexture()
    ui.setupUi(SoilTexture)
    SoilTexture.show()
    sys.exit(app.exec_())

